version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: voting-cache
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    networks:
      - backend
      - frontend
  voters-api:
    image: voters-api-better:v1
    container_name: voters-api-1
    restart: always
    ports:
      - '1080:1080'
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend
  polls-api:
    image: polls-api-better:v1
    container_name: polls-api-1
    restart: always
    ports:
      - '1090:1090'
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend
  votes-api:
    image: votes-api-better:v1
    container_name: votes-api-1
    restart: always
    ports:
      - '1100:1100'
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: true