version: '3.8'
services:
  cache:
    image: redis/redis-stack:latest
    container_name: voters-cache
    restart: on-failure
    ports:
      - '6379:6379'
      - '8001:8001'
    networks:
      - backend
      - frontend
  voters-api:
    image: mattgott1231/voters-api:v1
    container_name: voters-api-1
    restart: always
    ports:
      - '1080:1080'
    depends_on:
      - cache
    environment:
      - REDIS_URL=cache:6379
    networks:
      - frontend
      - backend
networks:
  frontend:
    internal: false
  backend:
    internal: true